### ISSUE TITLE
Potential race condition in Summary window rotation

### ISSUE THREAD

**Issue by dima-vm** [VictoriaMetrics/metrics-java#34]
The summary.update() might be called from multiple threads.
So the following lines in Summary rotate() might have race condition due to `currentWindow`:
```java
timeWindow[currentWindow] = new TimeWindow();
if (++currentWindow >= timeWindow.length) {
```

**Comment by dima-vm** [comment]
FYI @golgotha

**Comment by dima-vm** [comment]
I take another look at this, and I see now that current version Summary metric was a quick implementation to keep the parity, before implementing a proper fast algorithm for online quantiles. Probably makes sense to rather rewrite it all instead of trying to fix.

**Comment by golgotha** [comment]
> I take another look at this, and I see now that current version Summary metric was a quick implementation to keep the parity, before implementing a proper fast algorithm for online quantiles. Probably makes sense to rather rewrite it all instead of trying to fix.

I will think about after faster algorithm. Do you have some ideas?
